### PR TITLE
Help with banned access to own server

### PR DESCRIPTION
**Pull request by ghost**
Yeah pastebin is so coool! You actually see!?!... the characters there. Like blaCk on whiTe. In .PDF its only black and white..... booooooooh! And and  and its numbers in front of every row.. Imagine EVERY row.. WOW.. I close this now. No help here. Maybe not my intention either. More like who licks most ass in this virus creation association.. You won em92 Congrats!

### CODE REVIEW

**Comment by em92** [comment]
- close this pull request, 'cos it is not pull request
- open issue and post minqlx.log data to pastebin, not to pdf file 'cos it is unreadable

**Comment by ghost** [comment]
Ok.. I admit.. I did not close this.. I forgot "s" in close like clo.e.. silly me. And I admit.. It was not for the ass liking contest I posted this. -> It was to see some reactions to the fact that iiiiiiiiiiiif a total imbecile moron like polip can hijack my server. What happens that day 100 nine year old boys with one brain cell more than polip spiced with some ADHD gets the formula? Your back doors leaks.. everything leaks.. Therefore we can´t have nice things on internet. With that said I also admit.. I respect and admire you guys who has created such, well nice things on intern.. for quakeLive. But it has some flaws and some integrity like questions. And in wrong hands I see a real potential hazard. Ok.. I admit.. I know who polip is"this guy" It is the whatafackImCool admin on  Melodeiro´s servers. He likes to move around people in teams so you dont have a change to fulfill a whole match in same team. Thats ubercool! And permban server renter from their servers to. That is not so cool. And I admit!! When that f** joined my server I kickban him before you had said f*****. I honestly have 4 different bind macros to permban him. As I said  Im  grateful to have the possibilities to extend ql, hands down. But i am  even more  grateful for the .py script that opened up all privates on photobucket! <3 Yes that leaked to..  Tomorrow I delete my profile and then all this shit disappears.  That is a nice thing.

**Comment by em92** [comment]
Well, if you want to solve your problem, first of all, you should do as I said in previous message. PDF  has word wraps, that makes it hard to read. Pastebin doesn't have such problem. Posting minqlx.log is very easy task. Maybe even easier than generating pdf file from txt.

Also please less crying, accusing someone with "ass-licking" or "supporting virus creation" without proof. It will spoil the attitude to you and you will have less chance for help.

**Comment by ghost** [comment]
But don´t you understand. I don´t wanted help. I know that help was far away here. But I wanted to point on a problem that random unauthorized  people runs around with the formula to ban all server owners from their servers. And what more are unauthorized  people capable to do with  unofficial information that has handed over by very skilled creator for example. This lately very advanced update scripts that remotes in to servers without no ones knowledge. Scripts that add things to servers etcetera.. People who has server on a personal computer with bank transfer programs and ID´s and maybe a little cute picture when he deep throats hes girlfriend or girlfriend working big strap-on dildo in his poor number 2 and on his/shes parents grave promised not to post on internet. What shall these people be worried about? Did you not read my following post? Well soon time for deletion anyway so oust drink up it ends in 10 minutes and you don´t have to lie down.

**Comment by em92** [comment]
> I wanted to point on a problem that random unauthorized people runs around with the formula to ban all server owners from their servers.

**Comment by em92** [comment]
Clean your mind from garbage first. Telling that 
> random unauthorized people runs around with the formula to ban all server owners from their servers

and

> Pretty obvious minqlx has back doors

without a proof is crap-talking. This is opensource project where you can point the places that could lead to use it as backdoors. But you don't do it.

Also asking for help in first message and telling 

> I don´t wanted help.

in next ones is also crap-talking.
/voteban

**Comment by ghost** [comment]
Wow.... Like talking to a wall =D Ok ****face time for launch!

**Pull request closed without merging**
