### PR TITLE
Update python_embed.c

### PR DESCRIPTION
**Pull request by roasticle**
PyMinqlx_ForceWeaponWait added. Working with my plugin for maps with custom weapon spawn times to use g_weaponrespawn cvar instead.

### CODE REVIEW

**Comment by em92** [comment]
Example how it should look: https://github.com/MinoMino/minqlx/commit/842f77dfcf957254512dc8c0c3fda388f628e318

I have send pm to you in discord with explanation indents, function args and etc.

**Comment by MinoMino** [comment]
Thanks for the contribution.

**Comment by em92** [comment]
>  Couldn't there just a cvar like qlx_enforceWeaponRespawn
To make this cvar work, we need to find out original weapon respawn times after changing wait property of entity.

**Comment by em92** [comment]
>  Couldn't there just a cvar like qlx_enforceWeaponRespawn

To make this cvar work, we need to find out original weapon respawn times after changing wait property of entity.

**Comment by jwinett** [comment]
You mean how the map had them set?  In case they're going to be returned to what they were?

**Comment by em92** [comment]
> You mean how the map had them set?

Yes. Weapons can have individual respawn times and ignore g_weaponRespawn (like in Bitter Embrace, afaik).

**Comment by jwinett** [comment]
Reloading the map isn't enough?

**Comment by em92** [comment]
> Reloading the map isn't enough?

Just checked. **map_restart** returnes individual respawn times back.

**Pull request merged**
